version: '3.8'

services:
  uveitis-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uveitis_system
    ports:
      - "80:3001"
      - "3001:3001"
      - "8000:8000"
    environment:
      - PORT=3001
      - PYTHON_BACKEND_URL=http://127.0.0.1:8000/predict
    volumes:
      - sqlite_data:/app/server/db
      - uploads_data:/app/server/uploads
    restart: always

volumes:
  sqlite_data:
  uploads_data:
