version: '3.8'

services:
  uveitis-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uveitis_frontend
    ports:
      - "80:80"
      - "5173:80"
    restart: always
