/**
 * src/utils/agarwalCenters.js
 *
 * Canonical directory of the 5 Dr. Agarwal's Eye Hospital regional hubs & Uveitis specialists.
 * Joint initiative with Arqgene for AI-driven clinical screening & direct specialist routing.
 */

export const AGARWAL_CENTERS = [
  {
    id: "DR-AG-01",
    name: "Dr. Soundari S., MS, FMRF",
    title: "Senior Consultant - Uveitis & Ocular Immunology",
    hospital: "Dr. Agarwal's Eye Hospital - Cathedral Road (Chennai Main)",
    clinicName: "Dr. Agarwal's Eye Hospital - Cathedral Road (Chennai Main)",
    city: "Chennai",
    address: "19, Cathedral Road, Gopalapuram, Chennai, Tamil Nadu 600086",
    phone: "+91 44 4378 7777",
    email: "dr.soundari@agarwaleye.com",
    distance: "2.1 km away",
    rating: 4.9,
    reviews: 340,
    nextSlot: "Today, 3:30 PM",
    coords: { x: 38, y: 42 },
    badge: "Flagship Referral Hub",
    experience: "18+ Years",
    fellowship: "Sankara Nethralaya (FMRF)",
    role: "senior",
    roleLabel: "Senior Consultant",
    supervisorId: null,
    supervisorName: null,
    supervisor_id: null,
    supervisor_name: null,
    clinic: "Dr. Agarwal's Eye Hospital - Cathedral Road (Chennai Main)",
  },
  {
    id: "DR-AG-02",
    name: "Dr. Ramamurthy Sundar, DNB, FRCS",
    title: "Vitreo-Retina & Posterior Uveitis Specialist",
    hospital: "Dr. Agarwal's Eye Hospital - Indiranagar",
    clinicName: "Dr. Agarwal's Eye Hospital - Indiranagar",
    city: "Bengaluru",
    address: "100 Feet Road, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038",
    phone: "+91 80 4680 8800",
    email: "dr.ramamurthy@agarwaleye.com",
    distance: "5.4 km away",
    rating: 4.9,
    reviews: 285,
    nextSlot: "Tomorrow, 10:00 AM",
    coords: { x: 62, y: 28 },
    badge: "Advanced Vitreo-Retina Hub",
    experience: "15+ Years",
    fellowship: "Royal College of Surgeons (FRCS)",
    role: "senior",
    roleLabel: "Senior Consultant",
    supervisorId: null,
    supervisorName: null,
    supervisor_id: null,
    supervisor_name: null,
    clinic: "Dr. Agarwal's Eye Hospital - Indiranagar",
  },
  {
    id: "DR-AG-03",
    name: "Dr. V. Rajeshwari, MS",
    title: "Senior Consultant - Uveitis & Cornea",
    hospital: "Dr. Agarwal's Eye Hospital - Banjara Hills",
    clinicName: "Dr. Agarwal's Eye Hospital - Banjara Hills",
    city: "Hyderabad",
    address: "Road No. 2, Banjara Hills, Hyderabad, Telangana 500034",
    phone: "+91 40 6815 6500",
    email: "dr.rajeshwari@agarwaleye.com",
    distance: "7.8 km away",
    rating: 4.85,
    reviews: 195,
    nextSlot: "Today, 5:15 PM",
    coords: { x: 75, y: 68 },
    badge: "Ocular Surface & Uvea Center",
    experience: "14+ Years",
    fellowship: "Cornea & Ocular Immunology Fellowship",
    role: "senior",
    roleLabel: "Senior Consultant",
    supervisorId: null,
    supervisorName: null,
    supervisor_id: null,
    supervisor_name: null,
    clinic: "Dr. Agarwal's Eye Hospital - Banjara Hills",
  },
  {
    id: "DR-AG-04",
    name: "Dr. Anand Parthasarathy, MS, FICO",
    title: "Anterior Segment & Uveitis Specialist",
    hospital: "Dr. Agarwal's Eye Hospital - Velachery",
    clinicName: "Dr. Agarwal's Eye Hospital - Velachery",
    city: "Chennai",
    address: "147, Velachery Bypass Road, Velachery, Chennai, Tamil Nadu 600042",
    phone: "+91 44 4055 4055",
    email: "dr.anand@agarwaleye.com",
    distance: "9.2 km away",
    rating: 4.9,
    reviews: 215,
    nextSlot: "Thursday, 11:30 AM",
    coords: { x: 25, y: 55 },
    badge: "Rapid Triage Center",
    experience: "12+ Years",
    fellowship: "International Council of Ophthalmology (FICO)",
    role: "junior",
    roleLabel: "Junior Specialist (Fellow)",
    supervisorId: "DR-AG-01",
    supervisorName: "Dr. Soundari S., MS, FMRF",
    supervisor_id: "DR-AG-01",
    supervisor_name: "Dr. Soundari S., MS, FMRF",
    clinic: "Dr. Agarwal's Eye Hospital - Velachery",
  },
  {
    id: "DR-AG-05",
    name: "Dr. Preethi Govindarajan, MD",
    title: "Paediatric & Autoimmune Uveitis Specialist",
    hospital: "Dr. Agarwal's Eye Hospital - R.S. Puram",
    clinicName: "Dr. Agarwal's Eye Hospital - R.S. Puram",
    city: "Coimbatore",
    address: "D.B. Road, R.S. Puram, Coimbatore, Tamil Nadu 641002",
    phone: "+91 422 422 8800",
    email: "dr.preethi@agarwaleye.com",
    distance: "12.0 km away",
    rating: 4.85,
    reviews: 160,
    nextSlot: "Friday, 2:00 PM",
    coords: { x: 82, y: 38 },
    badge: "Immunology Specialty Wing",
    experience: "11+ Years",
    fellowship: "Paediatric Ophthalmology & Uveitis",
    role: "junior",
    roleLabel: "Junior Specialist (Resident)",
    supervisorId: "DR-AG-02",
    supervisorName: "Dr. Ramamurthy Sundar, DNB, FRCS",
    supervisor_id: "DR-AG-02",
    supervisor_name: "Dr. Ramamurthy Sundar, DNB, FRCS",
    clinic: "Dr. Agarwal's Eye Hospital - R.S. Puram",
  },
];
